/** Cross-cutting Soanas ACL features (POS permissions catalog — AUTH-POS-*). */
export const features = [
  { id: 'soanas_core.access', title: 'Access Soanas', module: 'soanas_core' },
  { id: 'soanas_core.profiles.view', title: 'View Soanas profiles', module: 'soanas_core', dependsOn: ['soanas_core.access'] },

  { id: 'soanas.pos.cash.open', title: 'Open cash session', module: 'soanas_core' },
  { id: 'soanas.pos.cash.close', title: 'Close cash session', module: 'soanas_core' },
  { id: 'soanas.pos.cash.withdrawal', title: 'Create cash withdrawal (sangria)', module: 'soanas_core' },
  { id: 'soanas.pos.cash.supply', title: 'Create cash supply', module: 'soanas_core' },
  { id: 'soanas.pos.cash.drawer_no_sale', title: 'Open drawer without sale', module: 'soanas_core' },
  { id: 'soanas.pos.item.cancel', title: 'Cancel POS item', module: 'soanas_core' },
  { id: 'soanas.pos.sale.cancel', title: 'Cancel POS sale', module: 'soanas_core' },
  { id: 'soanas.pos.discount.grant', title: 'Grant discount', module: 'soanas_core' },
  { id: 'soanas.pos.discount.over_limit', title: 'Approve discount over limit', module: 'soanas_core' },
  { id: 'soanas.pos.price.override', title: 'Override price', module: 'soanas_core' },
  { id: 'soanas.pos.sell.below_cost', title: 'Sell below cost', module: 'soanas_core' },
  { id: 'soanas.pos.sell.without_stock', title: 'Sell without stock', module: 'soanas_core' },
  { id: 'soanas.pos.sale.edit', title: 'Edit in-progress sale', module: 'soanas_core' },
  { id: 'soanas.pos.sale.reopen', title: 'Reopen sale', module: 'soanas_core' },
  { id: 'soanas.pos.payment.refund', title: 'Refund payment', module: 'soanas_core' },
  { id: 'soanas.pos.return.create', title: 'Create return', module: 'soanas_core' },
  { id: 'soanas.pos.credit.issue', title: 'Issue store credit', module: 'soanas_core' },
  { id: 'soanas.pos.fiscal.cancel', title: 'Cancel fiscal document', module: 'soanas_core' },
  { id: 'soanas.pos.fiscal.inutilize', title: 'Inutilize numbering', module: 'soanas_core' },
  { id: 'soanas.pos.stock.adjust', title: 'Adjust stock', module: 'soanas_core' },
  { id: 'soanas.pos.stock.inventory', title: 'Run inventory count', module: 'soanas_core' },
  { id: 'soanas.pos.view.cost', title: 'View cost', module: 'soanas_core' },
  { id: 'soanas.pos.view.margin', title: 'View margin', module: 'soanas_core' },
  { id: 'soanas.pos.view.revenue', title: 'View revenue', module: 'soanas_core' },
  { id: 'soanas.pos.view.profit', title: 'View profit', module: 'soanas_core' },
  { id: 'soanas.pos.cash.view_others', title: 'View other cashiers closings', module: 'soanas_core' },
  { id: 'soanas.pos.customers.manage', title: 'Manage customers from POS', module: 'soanas_core' },
  { id: 'soanas.pos.credit.limit', title: 'Change credit limit', module: 'soanas_core' },
  { id: 'soanas.pos.credit.approve', title: 'Approve store credit sale (fiado)', module: 'soanas_core' },
  { id: 'soanas.pos.fiscal.config', title: 'Edit fiscal configuration', module: 'soanas_core' },
  { id: 'soanas.pos.hardware.config', title: 'Edit hardware configuration', module: 'soanas_core' },
  { id: 'soanas.pos.approval.manager', title: 'Provide managerial approval', module: 'soanas_core' },
]

export default features
